[toolchain]
anchor_version = "0.31.1"

[programs.devnet]
flash_pred = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg3q2aW7v4Yk"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[profile.release]
overflow-checks = true